using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CellStore.Api;
using CellStore.Model;
using CellStore.Client;
using System.Reflection;

namespace CellStore.Test
{
    /// <summary>
    ///  Class for testing Outcome
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OutcomeTests
    {
        private Outcome instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Outcome();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Outcome
        /// </summary>
        [Test]
        public void OutcomeInstanceTest()
        {
            Assert.IsInstanceOf<Outcome> (instance, "instance is a Outcome");
        }

        
        /// <summary>
        /// Test the property 'Success' 
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO: unit test for the property 'Success' 
        }
        
        /// <summary>
        /// Test the property 'Description' 
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO: unit test for the property 'Description' 
        }
        

    }

}
